server:
  port: 8001

mybatis:
  configuration:
      call-setters-on-nulls: true
  #config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.csj.cloud.entities   # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml                       # mapper映射文件
spring:
  application:
    name: service-good
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&characterEncoding=utf-8           # 数据库名称
    username: root
    password: 123456
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://192.168.101.149:8761/eureka
#   instance:
#     instance-id: service-good
#     prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: service-good-8001
  company.name: www.i-wq.net
  build.artifactId: $project.artifactId$
  build.version: $project.version$

logging:
  level:
    com.csj.cloud.servicegood.dao.*: debug

######################### Druid连接池的配置信息  #################
spring.druid.initialSize: 5                                 #初始化连接大小
spring.druid.minIdle: 5                                     #最小连接池数量
spring.druid.maxActive: 20                                  #最大连接池数量
spring.druid.maxWait: 60000                                 #获取连接时最大等待时间，单位毫秒
spring.druid.timeBetweenEvictionRunsMillis: 60000           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.druid.minEvictableIdleTimeMillis: 300000             #配置一个连接在池中最小生存的时间，单位是毫秒
spring.druid.validationQuery: SELECT 1 FROM DUAL            #测试连接
spring.druid.testWhileIdle: true                            #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
spring.druid.testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
spring.druid.testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
spring.druid.poolPreparedStatements: false                  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
spring.druid.maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
spring.druid.filters: stat,wall,log4j,config                       #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
spring.druid.connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  #通过connectProperties属性来打开mergeSql功能;慢SQL记录
